- name: Install node and npm
  hosts: nodejs_servers
  become: yes
  tasks: 
    - name: Update apt repo
      apt : update_cache=yes force_apt_get=yes
    - name: Install nodejs and npm 
      apt:
       pkg:
         - nodejs
         - npm