- name: Install node, npm and pm2
  hosts: nodejs_servers
  become: yes
  tasks: 
    - name: Update apt repo
      apt : update_cache=yes force_apt_get=yes
    - name: Install nodejs and npm 
      apt:
       pkg:
         - nodejs
         - npm
        #  - python3-pip
    - name: Install pm2 server for nodeJS Application
      command: npm install pm2 -g
      # state: present
- name: deploy NodeJS App
  hosts: nodejs_servers
  become: yes 
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/amitmaurya07/nodejs-application.git'
        dest: /apps/nodejs-app  
        clone: yes
    # - name: Install package.json packages
    #   command: npm install
    #   args:
    #     chdir: /apps/nodejs-app/package.json
    - name: Run NodeJS Application
      command: pm2 startup
      command: pm2 start /apps/nodejs-app/app.js 
      command: pm2 save
      # args:
      #   chdir: /apps/nodejs-app/app.js
      # async: 1000
      # poll: 0
      