- name: Install node and npm
  hosts: nodejs_servers
  become: yes
  tasks: 
    - name: Update apt repo
      apt : update_cache=yes force_apt_get=yes
    - name: Install nodejs and npm 
      apt:
       pkg:
         - nodejs
         - npm
- name: deploy NodeJS App
  hosts: nodejs_servers
  become: yes 
  tasks:
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://nexus.neuralcompany.team/#browse/browse:npm-hosted:nodejs-app-amit%2Fnodejs-app-amit-0.0.1.tgz
        dest: /usr/local/bin
        remote_src: yes
    - name: Install package.json packages 
      command: npm install package.json
    - name: Run NodeJS Application
      command: npm start
      
      