- name: Install node and npm
  hosts: nodejs_servers
  become: yes
  tasks: 
    - name: Update apt repo
      apt : update_cache=yes force_apt_get=yes
    - name: Install nodejs and npm 
      apt:
       pkg:
         - nodejs
         - npm
- name: deploy NodeJS App
  hosts: nodejs_servers
  become: yes 
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/amitmaurya07/nodejs-application.git'
        dest: /apps/nodejs-app
        clone: yes
    # - name: Install package.json packages
    #   command: npm install
    #   args:
    #     chdir: /apps/nodejs-app/package.json
    - name: Run NodeJS Application
      command: npm start
      args:
        chdir: /apps/nodejs-app/
      async: 1000
      poll: 0
      