- name: Install node, npm and pm2
  hosts: nodejs_servers_version_v1
  become: yes
  tasks: 
    - name: Update apt repo
      apt : update_cache=yes force_apt_get=yes

    - name: Install nodejs and npm 
      apt:
       pkg:
         - nodejs
         - npm

- name: Deploy NodeJS App
  hosts: nodejs_servers_version_v1
  become_user: amitmau7878
  tasks:
    - name: Unarchive the Artifacts.
      unarchive:
        src: "http://localhost:8081/repository/npm-hosted/nodejs-app-amit/-/nodejs-app-amit-0.0.1.tgz"
        dest: /apps/nodejs-app
        remote_src: true