- name: Install node, npm and pm2
  hosts: nodejs_servers_version_v1
  become: yes
  tasks: 
    - name: Update apt repo
      apt : update_cache=yes force_apt_get=yes

    - name: Install nodejs and npm 
      apt:
       pkg:
         - nodejs
         - npm

    - name: Install pm2 server for nodeJS Application
      command: npm install pm2 -g

- name: Deploy NodeJS App
  hosts: nodejs_servers_version_v1
  become: yes 
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/amitmaurya07/nodejs-application.git'
        dest: /apps/nodejs-app  
        clone: yes
        version: amit/v1

    # - name: Pull from Nexus
    #   ansible.builtin.unarchive:
    #     src: "http://localhost:8081/repository/npm-hosted/nodejs-app-amit/-/nodejs-app-amit-0.0.1.tgz"
    #     dest: /apps/nodejs-app/
    #     remote_src: yes

    - name: 
    
    - name: Reload the daemon for node js application
      command: systemctl daemon-reload
    
    - name: Start the systemd application. 
      command: systemctl start /apps/nodejs-app/app.js

    - name: Stopping all pm2 servers 
      command: pm2 delete all

    - name: Startup the application through pm2 
      command: pm2 startup

    - name: Run NodeJS Application
      command: pm2 start -f /apps/nodejs-app/app.js 

    - name: Save the Current process so that when application will be rebooted, it will start the application
      command: pm2 save 